title: V najinih čevljih
description: Our blog

url: http://primozgodec.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Domov
   url: /index.html
 - title: Midva
   url: /about
 - title: Piši nama
   url: /contact

social:
   github: PrimozGodec
   twitter: primozG92
   facebook: primoz.godec

google_analytics: "UA-58855861-1"
